import "./globals.css";
import "../../node_modules/@hdfclife-insurance/one-x-ui/styles.css";
import { TableProvider } from "../context/tableContext.tsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TableProvider>{children}</TableProvider>
      </body>
    </html>
  );
}
