import "./globals.css";
import "../../node_modules/@hdfclife-insurance/one-x-ui/styles.css";
import { TableProvider } from "../context/tableContext";
import { ReactNode } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <TableProvider>{children}</TableProvider>
      </body>
    </html>
  );
}
